using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;

namespace UWPWeatherApp
{
    public class OpenWeatherMapProxy
    {
        public async static Task<RootObject> GetWeather(double lat, double lon) //task<> promise that when this is completed it will give back type RootObject
        {
            //key for open weather 0aab86a4a278c20065049e12a392756c
            //make call out to open weather
            var http = new HttpClient();
            var response = await http.GetAsync("http://samples.openweathermap.org/data/2.5/weather?lat=53.27&lon=9.05&appid=0aab86a4a278c20065049e12a392756c"); //53.2707° N, 9.0568° W galway
            var result = await response.Content.ReadAsStringAsync(); //result in a string format
            var serializer = new DataContractJsonSerializer(typeof(RootObject)); //To serlize and deserlize from Json

            var ms = new MemoryStream(Encoding.UTF8.GetBytes(result)); //json is encoded using UTF8
            var data = (RootObject)serializer.ReadObject(ms); //take usable data out of serializer

            return data;
        }
    }
    
    //generated by using Json2Csharp, the api call will populate
    [DataContract] //tells serializer to treat this like a class
    public class Coord
    {
        [DataMember] //tells serializer to treat this like a property
        public double lon { get; set; }
        [DataMember]
        public double lat { get; set; }
    }
    [DataContract]
    public class Weather
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string main { get; set; }
        [DataMember]
        public string description { get; set; }
        [DataMember]
        public string icon { get; set; }
    }
    [DataContract]
    public class Main
    {
        [DataMember]
        public double temp { get; set; }
        [DataMember]
        public double pressure { get; set; }
        [DataMember]
        public int humidity { get; set; }
        [DataMember]
        public double temp_min { get; set; }
        [DataMember]
        public double temp_max { get; set; }
        [DataMember]
        public double sea_level { get; set; }
        [DataMember]
        public double grnd_level { get; set; }
    }
    [DataContract]
    public class Wind
    {
        [DataMember]
        public double speed { get; set; }
        [DataMember]
        public int deg { get; set; }
    }
    [DataContract]
    public class Clouds
    {
        [DataMember]
        public int all { get; set; }
    }
    [DataContract]
    public class Sys
    {
        [DataMember]
        public double message { get; set; }
        [DataMember]
        public string country { get; set; }
        [DataMember]
        public int sunrise { get; set; }
        [DataMember]
        public int sunset { get; set; }
    }
    [DataContract]
    public class RootObject
    {
        [DataMember]
        public Coord coord { get; set; }
        [DataMember]
        public List<Weather> weather { get; set; }
        [DataMember]
        public string @base { get; set; }
        [DataMember]
        public Main main { get; set; }
        [DataMember]
        public Wind wind { get; set; }
        [DataMember]
        public Clouds clouds { get; set; }
        [DataMember]
        public int dt { get; set; }
        [DataMember]
        public Sys sys { get; set; }
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string name { get; set; }
        [DataMember]
        public int cod { get; set; }
    }
}
